### ISSUE TITLE
[Insight] Object parameters should be type hinted - in example/Service/UserAdapter.php, line 16

### ISSUE THREAD

**Issue by esterm** [nilportugues/php-eloquent-repository#2]
**[in example/Service/UserAdapter.php, line 16](https://github.com/nilportugues/php-eloquent-repository/blob/0bd24fe51348efd00b1e5b48baf7b653d6c2cfb9/example/Service/UserAdapter.php#L16)**

> The parameter `model`, which is an object, should be typehinted.

``` php
    /**
     * @param $model
     *
     * @return User
     */
    public function fromEloquent($model)
    {
        return new User(
            new UserId($model->id),
            $model->name,
            new DateTimeImmutable($model->created_at)
```

---

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/8d362f15-8385-40c0-a7a6-672c857352b4/analyses/4)_

**Comment by esterm** [comment]
Let me fix it!

**Comment by nilportugues** [comment]
https://github.com/PHPRepository/php-eloquent-repository/pull/3 :100:
